"""Concrete Graph node contracts used by Studio and codegen."""

from __future__ import annotations

from typing import Any

from .common import GEN_DOC, GEN_FULL, GEN_GLUE, GEN_PARTIAL

NODE_CONTRACTS: dict[str, dict[str, Any]] = {
    "hal.gpio_line_input": {
        "generation": GEN_FULL,
        "owner": "codegen",
        "required": ["id", "type", "channels", "pins"],
        "optional": ["bus_id", "module"],
        "generated": ["HAL ops", "mock line input read", "board pin constants"],
        "boundary": "Generates a mock GPIO line-input HAL; real board reads belong in board_adapters when replacing the mock path.",
    },
    "hal.custom": {
        "generation": GEN_FULL,
        "owner": "user-callback",
        "required_any": ["init", "read", "write", "ioctl"],
        "optional": ["hal_type", "bus_id", "ctx", "module"],
        "callbacks": {"init": "hal.init", "read": "hal.read", "write": "hal.write", "ioctl": "hal.ioctl"},
        "generated": ["HAL ops", "callback externs", "HAL registration"],
        "boundary": "Codegen registers the HAL; custom_files or board_adapters implement the callbacks.",
    },
    "sensor.line_tracking": {
        "generation": GEN_FULL,
        "owner": "codegen",
        "required": ["id", "type", "input"],
        "optional": ["module"],
        "generated": ["sensor ops", "HAL-bound line sensor read"],
        "boundary": "Input must reference hal.gpio_line_input; LineFollower flows consume this sensor.",
    },
    "sensor.custom": {
        "generation": GEN_FULL,
        "owner": "user-callback",
        "required": ["id", "type", "read"],
        "optional": ["sensor_type", "channel_count", "hal_name", "comm_name", "ctx", "init", "module"],
        "callbacks": {"init": "sensor.init", "read": "sensor.read"},
        "generated": ["sensor ops", "callback externs", "sensor registration"],
        "boundary": "Codegen registers the sensor; custom read/init callbacks convert real data into the agreed payload.",
    },
    "actuator.motor": {
        "generation": GEN_FULL,
        "owner": "codegen",
        "required": ["id", "type", "pwm", "dir_pin"],
        "optional": ["module"],
        "generated": ["motor actuator ops", "mock speed/direction write", "PWM/DIR constants"],
        "boundary": "Generated motor write is host-checkable mock glue; real PWM/GPIO writes belong in board adaptation.",
    },
    "actuator.custom": {
        "generation": GEN_FULL,
        "owner": "user-callback",
        "required": ["id", "type", "write"],
        "optional": ["actuator_type", "hal_name", "comm_name", "ctx", "init", "enable", "disable", "module"],
        "callbacks": {"init": "actuator.init", "enable": "actuator.enable", "disable": "actuator.disable", "write": "actuator.write"},
        "generated": ["actuator ops", "callback externs", "actuator registration"],
        "boundary": "Codegen registers the actuator; custom callbacks implement device behavior.",
    },
    "algorithm.pid": {
        "generation": GEN_FULL,
        "owner": "codegen",
        "required": ["id", "type"],
        "optional": ["kp", "ki", "kd", "kff", "integral_min", "integral_max", "out_min", "out_max", "anti_windup", "module"],
        "generated": ["PID context", "algorithm ops", "algorithm registration"],
        "boundary": "Uses the EFW built-in PID API; no user callback is required.",
    },
    "algorithm.custom": {
        "generation": GEN_FULL,
        "owner": "user-callback",
        "required": ["id", "type", "run"],
        "optional": ["algo_type", "ctx", "io_contract", "module"],
        "callbacks": {"run": "algorithm.run"},
        "generated": ["algorithm ops", "callback extern", "algorithm registration"],
        "boundary": "Codegen registers the algorithm; run callback owns business math. LineFollower requires io_contract=efw_pid.",
    },
    "module.custom": {
        "generation": GEN_FULL,
        "owner": "user-callback",
        "required": ["id", "type"],
        "optional": ["module_type", "ctx", "init", "start", "stop", "poll", "module"],
        "callbacks": {"init": "module.lifecycle", "start": "module.lifecycle", "stop": "module.lifecycle", "poll": "module.lifecycle"},
        "generated": ["module ops", "callback externs", "module lifecycle registration/poll"],
        "boundary": "Codegen owns lifecycle wiring; user callbacks own module behavior.",
    },
    "task.periodic": {
        "generation": GEN_FULL,
        "owner": "scheduler",
        "required_any": ["call", "flow"],
        "optional": ["period_ms", "module"],
        "callbacks": {"call": "task.call"},
        "generated": ["tick scheduler entry", "task callback extern"],
        "boundary": "period_ms must be a multiple of project.tick_ms; task can call a user function or schedule a flow.",
    },
    "project.module": {
        "generation": GEN_DOC,
        "owner": "studio",
        "required": ["id", "type"],
        "optional": ["display_name", "description", "inputs", "outputs", "subgraph"],
        "generated": [],
        "boundary": "Current module nodes organize pages and ownership; they are not independent compilation units yet.",
    },
    "event.topic": {
        "generation": GEN_PARTIAL,
        "owner": "codegen",
        "required": ["id", "type", "topic_id"],
        "optional": ["payload_type", "description", "module"],
        "generated": ["APP_TOPIC_* macro"],
        "boundary": "Defines a topic ID. Publish calls still belong in user code unless a task/module callback emits them.",
    },
    "event.publisher": {
        "generation": GEN_DOC,
        "owner": "user-code",
        "required": ["id", "type", "topic"],
        "optional": ["source", "target", "data_expr", "size_expr", "module"],
        "generated": [],
        "boundary": "Documents publish intent. The actual efw_topic_publish call is written in custom_files/module/task code.",
    },
    "event.subscriber": {
        "generation": GEN_PARTIAL,
        "owner": "user-callback",
        "required": ["id", "type", "topic", "callback"],
        "optional": ["target", "user", "module"],
        "callbacks": {"callback": "topic.callback"},
        "generated": ["efw_topic_subscribe binding", "callback extern"],
        "boundary": "Codegen subscribes the callback; user code implements the callback body.",
    },
    "state.machine": {
        "generation": GEN_GLUE,
        "owner": "codegen",
        "required": ["id", "type"],
        "optional": ["initial", "description", "module"],
        "generated": ["state table glue", "current-state index"],
        "boundary": "Lightweight generated state runner, not a full runtime state-machine engine.",
    },
    "state.state": {
        "generation": GEN_GLUE,
        "owner": "user-callback",
        "required": ["id", "type", "machine"],
        "optional": ["on_enter", "on_update", "on_exit", "module"],
        "callbacks": {"on_enter": "state.lifecycle", "on_update": "state.lifecycle", "on_exit": "state.lifecycle"},
        "generated": ["efw_state_machine_ops_t entry"],
        "boundary": "State callbacks are user-owned; codegen only wires enter/tick/exit calls.",
    },
    "state.transition": {
        "generation": GEN_GLUE,
        "owner": "user-callback",
        "required": ["id", "type", "machine", "from", "to", "condition"],
        "optional": ["priority", "timeout_ms", "event_trigger", "action", "module"],
        "callbacks": {"condition": "condition", "action": "transition.action"},
        "generated": ["conditional transition glue"],
        "boundary": "Condition is required and user-owned. event_trigger is currently a generated comment/semantic marker.",
    },
    "logic.if": {
        "generation": GEN_GLUE,
        "owner": "user-callback",
        "required": ["id", "type"],
        "optional": ["condition", "then", "else", "period_ms", "module"],
        "callbacks": {"condition": "condition", "then": "logic.call", "else": "logic.call"},
        "generated": ["app_logic_<id>() wrapper"],
        "boundary": "Generated wrapper calls user condition/branches; it does not infer business logic.",
    },
    "logic.loop": {
        "generation": GEN_GLUE,
        "owner": "user-callback",
        "required": ["id", "type"],
        "optional": ["condition", "body", "max_iterations", "period_ms", "module"],
        "callbacks": {"condition": "condition", "body": "logic.call"},
        "generated": ["guarded app_logic_<id>() loop wrapper"],
        "boundary": "max_iterations protects the bare-metal loop; loop condition/body are user-owned.",
    },
    "logic.switch": {
        "generation": GEN_DOC,
        "owner": "user-code",
        "required": ["id", "type"],
        "optional": ["module", "expression", "cases", "default", "description"],
        "generated": [],
        "boundary": "Documents a switch-style decision block. Implement the actual switch in custom_files until codegen grows full switch glue.",
    },
    "logic.for": {
        "generation": GEN_DOC,
        "owner": "user-code",
        "required": ["id", "type"],
        "optional": ["module", "iterator", "start", "end", "step", "body", "description"],
        "generated": [],
        "boundary": "Documents a bounded for-loop block. Implement the actual loop in custom_files until codegen grows full for-loop glue.",
    },
    "data.enum": {
        "generation": GEN_DOC,
        "owner": "user-code",
        "required": ["id", "type", "name"],
        "optional": ["module", "values", "description"],
        "generated": [],
        "boundary": "Documents an enum type used by the project. Define the actual C enum in custom_files or board_adapters.",
    },
    "data.struct": {
        "generation": GEN_DOC,
        "owner": "user-code",
        "required": ["id", "type", "name"],
        "optional": ["module", "fields", "description"],
        "generated": [],
        "boundary": "Documents a struct payload/config type. Define the actual C struct in custom_files or board_adapters.",
    },
    "custom.card": {
        "generation": GEN_DOC,
        "owner": "studio",
        "required": ["id", "type"],
        "optional": ["title", "description", "module"],
        "generated": [],
        "boundary": "Pure documentation card; no C output.",
    },
    "custom.code": {
        "generation": GEN_DOC,
        "owner": "user-code",
        "required": ["id", "type"],
        "optional": ["path", "description", "module"],
        "generated": [],
        "boundary": "Documents a code relationship. Actual source content is stored in custom_files or board_adapters.",
    },
}

SUPPORTED_NODE_TYPES = set(NODE_CONTRACTS)
