/**
 * @file    app_state_machines.c
 * @brief   Generated state machine definitions and logic.
 *
 * @warning THIS FILE IS AUTO-GENERATED BY EFW CODEGEN.
 *          DO NOT EDIT MANUALLY — your changes will be overwritten.
 */

#include "app_bootstrap.h"
#include "app_manifest.h"
#include "efw/efw.h"
#include <string.h>

/* ======================================================================
 *  Helper functions
 * ====================================================================== */
$STATE_HELPERS
/* ======================================================================
 *  State machine definitions
 * ====================================================================== */
$STATE_LOGIC_BLOCKS
