/**
 * @file    app_platform.c
 * @brief   Generated platform registration layer. Board I/O lives in board_adapters.
 *
 * @warning THIS FILE IS AUTO-GENERATED BY EFW CODEGEN.
 *          DO NOT EDIT MANUALLY — your changes will be overwritten.
 */

#include "app_platform.h"
#include "app_manifest.h"

#ifndef EFW_NULL_NAME
#define EFW_NULL_NAME 0
#endif

/* ======================================================================
 *  External callbacks
 * ====================================================================== */
$EXTERNS
/* ======================================================================
 *  Type helpers
 * ====================================================================== */
$TYPE_HELPERS
/* ======================================================================
 *  HAL definitions
 * ====================================================================== */
$HAL_DEFS
/* ======================================================================
 *  Sensor definitions
 * ====================================================================== */
$SENSOR_DEFS
/* ======================================================================
 *  Actuator definitions
 * ====================================================================== */
$ACTUATOR_DEFS
/* ======================================================================
 *  Registration
 * ====================================================================== */
$REGISTRATIONS
/* ======================================================================
 *  Deprecated line state setter
 * ====================================================================== */
void app_platform_set_line_state(const char *input_name, const uint16_t *values, uint8_t count) {
    (void)values;
    if (!input_name) return;
$LINE_STATE_BODY}
