/**
 * @file    app_events.c
 * @brief   Generated event queue runtime using EFW framework API.
 *
 * @warning THIS FILE IS AUTO-GENERATED BY EFW CODEGEN.
 *          DO NOT EDIT MANUALLY — your changes will be overwritten.
 */

#include "app_bootstrap.h"
#include "app_manifest.h"
#include "efw/efw.h"
#include <string.h>

/* ======================================================================
 *  Event dispatch context (for current_event_name/topic_id accessors)
 * ====================================================================== */
static const char *g_app_event_name;
static uint16_t g_app_event_topic_id;
static const void *g_app_event_data;
static uint16_t g_app_event_size;

const char *app_current_event_name(void) { return g_app_event_name; }
uint16_t app_current_event_topic_id(void) { return g_app_event_topic_id; }
const void *app_current_event_data(void) { return g_app_event_data; }
uint16_t app_current_event_size(void) { return g_app_event_size; }

/* ======================================================================
 *  Event dispatch callback (used by efw_event_queue_process_ex)
 * ====================================================================== */
$EVENT_DISPATCH_FN
/* ======================================================================
 *  Event API wrappers
 * ====================================================================== */
efw_status_t app_post_event(const char *event_name, uint16_t topic_id,
                            const void *data, uint16_t size) {
    return efw_event_queue_post_named(topic_id, event_name, data, size);
}

efw_status_t app_process_event_queue(void) {
    return efw_event_queue_process_ex(app_dispatch_event_fn);
}
