/**
 * @file    app_publishers.c
 * @brief   Generated publisher runtime: cache, auto-commit, publish API.
 *
 * @warning THIS FILE IS AUTO-GENERATED BY EFW CODEGEN.
 *          DO NOT EDIT MANUALLY — your changes will be overwritten.
 */

#include "app_bootstrap.h"
#include "app_manifest.h"
#include <string.h>

/* ======================================================================
 *  Dataflow buffer
 * ====================================================================== */
typedef union {
    uint8_t raw[APP_DATAFLOW_BUFFER_SIZE];
    float align_f;
    uint32_t align_u32;
    void *align_ptr;
} app_dataflow_buffer_t;

/* ======================================================================
 *  Publisher cache and auto-commit
 * ====================================================================== */
$PUBLISHER_RUNTIME
/* ======================================================================
 *  Dataflow pipelines
 * ====================================================================== */
$DATAFLOW_PIPELINES
/* ======================================================================
 *  Line follower definitions
 * ====================================================================== */
$LINE_FOLLOWER_DEFS
