/**
 * @file    app_bootstrap.c
 * @brief   Generated core: pools, init, manifest, entry points.
 *
 * @warning THIS FILE IS AUTO-GENERATED BY EFW CODEGEN.
 *          DO NOT EDIT MANUALLY — your changes will be overwritten.
 */

#include "app_bootstrap.h"

#include "app_components.h"
#include "app_manifest.h"
#include "app_platform.h"
#include "efw/app/runtime.h"
#include <string.h>

/* ======================================================================
 *  Registry pools
 * ====================================================================== */
#if APP_USE_HAL
static const efw_hal_ops_t *g_hal_pool[APP_HAL_COUNT];
#endif
#if APP_USE_SENSOR
static const efw_sensor_ops_t *g_sensor_pool[APP_SENSOR_COUNT];
#endif
#if APP_USE_ACTUATOR
static const efw_actuator_ops_t *g_actuator_pool[APP_ACTUATOR_COUNT];
#endif
#if APP_USE_ALGORITHM
static const efw_algo_ops_t *g_algo_pool[APP_ALGO_COUNT];
#endif
#if APP_USE_MODULE
static const efw_module_ops_t *g_module_pool[APP_MODULE_COUNT];
#endif

/* ======================================================================
 *  Global state
 * ====================================================================== */
static uint32_t g_app_elapsed_ms;

/* ======================================================================
 *  Contract ABI checks
 * ====================================================================== */
$CONTRACT_SIZE_CHECKS
/* ======================================================================
 *  External declarations
 * ====================================================================== */
$EXTERNS
/* ======================================================================
 *  Pool initialization
 * ====================================================================== */
static efw_status_t app_init_pools(void) {
    efw_status_t s;
#if APP_USE_HAL
    s = efw_hal_registry_init_pool(g_hal_pool, APP_HAL_COUNT);
    if (s != EFW_OK) return s;
#endif
#if APP_USE_SENSOR
    s = efw_sensor_registry_init_pool(g_sensor_pool, APP_SENSOR_COUNT);
    if (s != EFW_OK) return s;
#endif
#if APP_USE_ACTUATOR
    s = efw_actuator_registry_init_pool(g_actuator_pool, APP_ACTUATOR_COUNT);
    if (s != EFW_OK) return s;
#endif
#if APP_USE_ALGORITHM
    s = efw_algo_registry_init_pool(g_algo_pool, APP_ALGO_COUNT);
    if (s != EFW_OK) return s;
#endif
#if APP_USE_MODULE
    s = efw_module_registry_init_pool(g_module_pool, APP_MODULE_COUNT);
    if (s != EFW_OK) return s;
#endif
    return EFW_OK;
}

/* ======================================================================
 *  Handle binding and scheduler
 * ====================================================================== */
$BIND_HANDLES$SCHEDULER_RUNTIME
/* ======================================================================
 *  Application manifest
 * ====================================================================== */
static const efw_app_manifest_t g_app_manifest = {
    .init_pools          = app_init_pools,
    .register_platform   = app_platform_register,
    .register_components = app_components_register,
    .bind_handles        = app_bind_handles,
    .update_1ms          = app_update_1ms,
};

/* ======================================================================
 *  Application entry points
 * ====================================================================== */
efw_status_t app_init(void) {
    efw_status_t s = efw_app_init(&g_app_manifest);
    if (s != EFW_OK) return s;
#if APP_USE_MODULE
    s = efw_module_init_all();
    if (s != EFW_OK) return s;
    s = efw_module_start_all();
    if (s != EFW_OK) return s;
#endif
    return EFW_OK;
}

efw_status_t app_loop_tick(void) {
    return efw_app_update_1ms(&g_app_manifest);
}

efw_status_t app_loop_1ms(void) {
    return app_loop_tick();
}

efw_status_t app_poll_forever(void) {
    for (;;) {
        efw_status_t s = app_loop_tick();
        if (s != EFW_OK) return s;
    }
}

efw_status_t app_main(void) {
    efw_status_t s = app_init();
    if (s != EFW_OK) return s;
    return app_poll_forever();
}
