/**
 * @file    app_components.c
 * @brief   Generated algorithm and module registration.
 *
 * @warning THIS FILE IS AUTO-GENERATED BY EFW CODEGEN.
 *          DO NOT EDIT MANUALLY — your changes will be overwritten.
 */

#include "app_components.h"
#include "app_manifest.h"
#include "app_bootstrap.h"

/* ======================================================================
 *  Algorithm definitions
 * ====================================================================== */
$ALGORITHM_RUNTIME_DEFS
/* ======================================================================
 *  Custom module definitions
 * ====================================================================== */
$CUSTOM_MODULE_RUNTIME_DEFS
/* ======================================================================
 *  Project module definitions
 * ====================================================================== */
$PROJECT_MODULE_RUNTIME_DEFS
/* ======================================================================
 *  Component registration
 * ====================================================================== */
efw_status_t app_components_register(void) {
    efw_status_t s;
$ALGORITHM_REGISTRATIONS$CUSTOM_MODULE_REGISTRATIONS$PROJECT_MODULE_REGISTRATIONS    return EFW_OK;
}
