"""Curated component metadata for framework palette cards.

The visual studio still supports conservative header discovery, but generated
cards should prefer explicit metadata whenever it exists.  These entries state
which fields a card needs, which callbacks are expected, and whether the current
generator can emit complete glue for the component.
"""

from __future__ import annotations

from typing import Any

COMPONENT_METADATA: dict[str, dict[str, Any]] = {
    "scan.hal.gpio": {
        "id": "hal_gpio",
        "type": "hal.custom",
        "hal_type": "gpio",
        "init": "app_hal_gpio_init",
        "read": "app_hal_gpio_read",
        "write": "app_hal_gpio_write",
        "callbacks": ["init", "read", "write", "ioctl"],
        "schema_fields": ["id", "type", "hal_type", "init", "read", "write", "ioctl", "ctx_name"],
        "includes": ["include/efw/hal/hal.h"],
        "requires_macros": ["EFW_ENABLE_HAL"],
        "library_module": "hal",
        "scan_quality": "component-metadata",
        "generation": "完整生成 HAL 注册 glue；板级读写由 custom_files 或 board_adapters 实现。",
    },
    "scan.hal.uart": {
        "id": "hal_uart",
        "type": "hal.custom",
        "hal_type": "uart",
        "init": "app_hal_uart_init",
        "read": "app_hal_uart_read",
        "write": "app_hal_uart_write",
        "callbacks": ["init", "read", "write", "ioctl"],
        "schema_fields": ["id", "type", "hal_type", "init", "read", "write", "ioctl", "ctx_name"],
        "includes": ["include/efw/hal/hal.h"],
        "requires_macros": ["EFW_ENABLE_HAL"],
        "library_module": "hal",
        "scan_quality": "component-metadata",
        "generation": "完整生成 UART HAL 注册 glue；收发缓冲与串口驱动由用户代码实现。",
    },
    "scan.sensor.custom": {
        "id": "sensor_custom",
        "type": "sensor.custom",
        "sensor_type": "custom",
        "read": "app_sensor_custom_read",
        "callbacks": ["init", "read"],
        "schema_fields": ["id", "type", "sensor_type", "hal_name", "init", "read", "ctx_name"],
        "includes": ["include/efw/device/sensor/custom.h", "include/efw/device/sensor.h"],
        "requires_macros": ["EFW_ENABLE_SENSOR"],
        "library_module": "sensor",
        "scan_quality": "component-metadata",
        "generation": "完整生成 custom sensor 注册 glue；read 回调签名会被 codegen 校验。",
    },
    "scan.actuator.custom": {
        "id": "actuator_custom",
        "type": "actuator.custom",
        "actuator_type": "custom",
        "write": "app_actuator_custom_write",
        "callbacks": ["init", "enable", "disable", "write"],
        "schema_fields": ["id", "type", "actuator_type", "hal_name", "init", "enable", "disable", "write", "ctx_name"],
        "includes": ["include/efw/device/actuator.h"],
        "requires_macros": ["EFW_ENABLE_ACTUATOR"],
        "library_module": "actuator",
        "scan_quality": "component-metadata",
        "generation": "完整生成 custom actuator 注册 glue；write 回调签名会被 codegen 校验。",
    },
    "scan.algorithm.pid": {
        "id": "pid_controller",
        "type": "algorithm.pid",
        "kp": 1.0,
        "ki": 0.0,
        "kd": 0.0,
        "out_min": -100.0,
        "out_max": 100.0,
        "schema_fields": ["id", "type", "kp", "ki", "kd", "out_min", "out_max", "integral_min", "integral_max"],
        "includes": ["include/efw/algorithm/control/pid.h"],
        "requires_macros": ["EFW_ENABLE_ALGORITHM"],
        "library_module": "algorithm",
        "callbacks": [],
        "scan_quality": "component-metadata",
        "generation": "完整生成 PID 配置、实例与算法注册。",
    },
    "scan.algorithm.custom": {
        "id": "algo_custom",
        "type": "algorithm.custom",
        "algo_type": "EFW_ALGO_CUSTOM",
        "run": "app_algo_custom_run",
        "io_contract": "custom",
        "callbacks": ["run"],
        "schema_fields": ["id", "type", "algo_type", "run", "ctx_name", "io_contract"],
        "includes": ["include/efw/algorithm/algorithm.h"],
        "requires_macros": ["EFW_ENABLE_ALGORITHM"],
        "library_module": "algorithm",
        "scan_quality": "component-metadata",
        "generation": "完整生成 custom algorithm 注册 glue；run 回调签名会被 codegen 校验。",
    },
    "scan.module.service": {
        "id": "module_service",
        "type": "module.custom",
        "module_type": "EFW_MODULE_SERVICE",
        "init": "app_module_service_init",
        "poll": "app_module_service_poll",
        "callbacks": ["init", "start", "stop", "poll"],
        "schema_fields": ["id", "type", "module_type", "init", "start", "stop", "poll", "ctx_name"],
        "includes": ["include/efw/module/module.h"],
        "requires_macros": ["EFW_ENABLE_MODULE"],
        "library_module": "module",
        "scan_quality": "component-metadata",
        "generation": "完整生成 module 注册和生命周期调用 glue。",
    },
    "scan.event.topic": {
        "id": "topic_event",
        "type": "event.topic",
        "topic_id": 1,
        "payload_type": "custom",
        "callbacks": [],
        "schema_fields": ["id", "type", "topic_id", "payload_type"],
        "includes": ["include/efw/core/event.h"],
        "requires_macros": ["EFW_ENABLE_EVENT"],
        "library_module": "event",
        "scan_quality": "component-metadata",
        "generation": "生成 topic 宏；发布/订阅关系通过 event.publisher/subscriber 表达。",
    },
    "scan.state.machine": {
        "id": "scanned_state_machine",
        "type": "state.machine",
        "initial": "idle",
        "callbacks": ["on_enter", "on_update", "on_exit"],
        "schema_fields": ["id", "type", "initial", "description"],
        "includes": ["include/efw/state/state_machine.h"],
        "requires_macros": ["EFW_ENABLE_STATE_MACHINE"],
        "library_module": "state",
        "scan_quality": "component-metadata",
        "generation": "生成轻量状态机 glue；状态和转换在状态机页面内添加。",
    },
}
